/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/admin/applications': RouteRecordInfo<'/admin/applications', '/admin/applications', Record<never, never>, Record<never, never>>,
    '/admin/clients': RouteRecordInfo<'/admin/clients', '/admin/clients', Record<never, never>, Record<never, never>>,
    '/admin/dashboard': RouteRecordInfo<'/admin/dashboard', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    '/admin/loan-products': RouteRecordInfo<'/admin/loan-products', '/admin/loan-products', Record<never, never>, Record<never, never>>,
    '/admin/login': RouteRecordInfo<'/admin/login', '/admin/login', Record<never, never>, Record<never, never>>,
    '/admin/payments': RouteRecordInfo<'/admin/payments', '/admin/payments', Record<never, never>, Record<never, never>>,
    '/client/apply': RouteRecordInfo<'/client/apply', '/client/apply', Record<never, never>, Record<never, never>>,
    '/client/dashboard': RouteRecordInfo<'/client/dashboard', '/client/dashboard', Record<never, never>, Record<never, never>>,
    '/client/loans': RouteRecordInfo<'/client/loans', '/client/loans', Record<never, never>, Record<never, never>>,
    '/client/login': RouteRecordInfo<'/client/login', '/client/login', Record<never, never>, Record<never, never>>,
    '/client/payments': RouteRecordInfo<'/client/payments', '/client/payments', Record<never, never>, Record<never, never>>,
    '/client/profile': RouteRecordInfo<'/client/profile', '/client/profile', Record<never, never>, Record<never, never>>,
    '/client/register': RouteRecordInfo<'/client/register', '/client/register', Record<never, never>, Record<never, never>>,
    '/CreateHealthRecord': RouteRecordInfo<'/CreateHealthRecord', '/CreateHealthRecord', Record<never, never>, Record<never, never>>,
  }
}
